export const ON_AUTH_FORM_FIELD_CHANGE = "ON_AUTH_FORM_FIELD_CHANGE"
export const LOGIN_REQUEST = "LOGIN_REQUEST"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS"
export const LOGOUT = "LOGOUT"
export const LOGIN_FAILURE = "LOGIN_FAILURE"


