# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

platform :ios, '8.0'

target 'ReactProject' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  pod 'React', path: '../node_modules/react-native', :subspecs => [
    'Core',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTGeolocation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket'
  ]

  # Pods for Microsoft Mobile center
  pod 'RNMobileCenter', '~> 0.1.0'
  pod 'MobileCenter', '~> 0.3.0'

  # react-native-image-crop-picker
  pod 'RSKImageCropper'
  pod 'QBImagePickerController'

  # react-native-maps
  pod 'react-native-maps', :path => '../node_modules/react-native-maps'

end
